// Generated by CoffeeScript 1.12.4
var Keyboard;

Keyboard = require("./Keyboard");

Keyboard.dismiss = require("dismissKeyboard");

Keyboard.AvoidingView = require("./AvoidingView");

module.exports = Keyboard;
